# Generated by Django 3.2 on 2021-04-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
